import { Metadata } from "next";
import { Angkor, Belgrano } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Saloon Game",
  description: "Generated by create next app",
};

export const angkor = Angkor({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const belgrano = Belgrano({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

// Layout component needs to return the correct React type for `children`
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${angkor.className} bg-[#caa469]`}>
        {children}
      </body>
    </html>
  );
}
